### ISSUE TITLE
ConfigOverrideSet behavior is inconsistent when using dicts

### ISSUE THREAD

**Issue by sagiepud** [shx2/figura#3]
The problem is demonstrated in the following example: 
This behavior makes sense to me - 
```python
config = ConfigContainer(a = 1) 
config.nested1 = ConfigContainer(b = 1)  # nested1 is a ConfigContainer
over1 = ConfigOverrideSet(nested1__b = 2, nested2__c = 2)
config.apply_overrides(over1)  # nested1 and nested2 are ConfigContainer's
```
This does not - 
```python
config = ConfigContainer(a = 1)
config.nested1 = ConfigContainer(b = 1)  # nested1 is a ConfigContainer
over2 = ConfigOverrideSet({'nested1': {'b': 2}, 'nested2': {'c': 2}})
config.apply_overrides(over2)  # nested1 and nested2 are dicts
```

Since using dicts as overrides seems to be supported (the new values do override their originals), I'd expect that applying the overrides wouldn't disrupt the ConfigContainer's structure. I imagine this could be handled either in the ConfigOverrideSet ctor, or in the apply_overrides function.

**Comment by shx2** [comment]
Your code works as designed.  Using dicts in place of override sets is not supported.

Dicts can be used for creating override sets (e.g. `ConfigOverrideSet(dct)` or `ConfigOverrideSet(**dct)`, etc.), but, as you demonstrated, this handles the dict shallowly, so the inner dicts are interpreted as values (of type dict), rather than override sets.  This is intentional, for avoiding override-set/dict (and config-container/dict) confusion.

The recommended way of deep-converting dicts to override sets, is using [ConfigOverrideSet.from_dict](http://figura.readthedocs.io/en/latest/figura.html#figura.container.ConfigContainerMixin.from_dict).

E.g.:

```
config = ConfigContainer.from_dict({'a': 1, 'nested1': {'b': 1}})
over2 = ConfigOverrideSet.from_dict({'nested1': {'b': 2}, 'nested2': {'c': 2}})
print(type(config.nested1), type(over2.nested1))
config.apply_overrides(over2)
print(type(config.nested1))

```
